### ISSUE TITLE
[Loan List] Loan is not marked overdue when next due date is past

### ISSUE THREAD

**Issue by qualitypal** [Visionary-Versatilist/SmallFinance#23]
Description
=========
Loans are not marked/shown as overdue even when due date is past

Steps to Reproduce
==============
1. Login into lendstack as superadmin
2. On Dashboard, click on Loans
3. Click on "Add Loan"
4. Select past date for "Start Date"
5. Click on Save

Actual Result
==========
Newly created loans with past start date shall be marked/shown as "Due"
Expected Result
============
Newly created loans with past start date shall be marked/shown as "Overdue"

Test Environment
=============
Browser: Chrome
Instance: Local
Node: 14.17.6
OS: Mac

<img width="277" alt="image" src="https://user-images.githubusercontent.com/82005110/159131531-5ec861d2-df52-45d4-9cba-696fba5ccd5c.png">

**Comment by Krithika-flink** [comment]
Its a workaround for lenders. Not required to be marked as overdue.

**Comment by qualitypal** [comment]
OK
