### ISSUE TITLE
[Add Loan]Fields in Add loan page differs

### ISSUE THREAD

**Issue by qualitypal** [Visionary-Versatilist/SmallFinance#40]
# Description
Fields in Add loan page differs when "Installment Calcuator" is selected

# Steps to Reproduce
1. Login into Lendstack as superadmin
2. Click on Loan in left sidebar
3. Click on Add Loan button
4. Select "Installment Calculator" drop down on the top right corner
5. Capture the screenshot of the page
6. Select Manual Entry for the drop down at the top right corner
7. Capture the screenshot of the page
8. Compare the fields in screenshots take in step 5 & step 7

# Actual Result
<img width="332" alt="image" src="https://user-images.githubusercontent.com/82005110/163674941-e15d7234-e12e-4f25-bfc5-bc7da1b0064f.png">
*X indicates the field is available in the page*

In addition, the big green circle show "total amount paid" when manual entry is selected and it shows "Installment Amount" when "Installment Calculator" is selected

# Expected result
Fields shown shall be consistent between manual entry and installent calculation options

# Test Environment
Instance: Staging
Browser: Chrome
OS: Mac

Add Loan page - Manual Entry
<img width="1380" alt="image" src="https://user-images.githubusercontent.com/82005110/163674739-f3e67f30-9856-4150-a9e9-d0a90a8ae871.png">

Add Loan Page - Installment Calculator
<img width="1489" alt="image" src="https://user-images.githubusercontent.com/82005110/163674766-e2f269b0-1a89-4ad8-9693-f05e2342705f.png">

**Comment by Krithika-flink** [comment]
As per the Requirement given, Both the pages have been designed. They are designed like that for a purpose.
