### ISSUE TITLE
[Add Loan] Only monthly option is available for Loan Tenure when "Installment Calculator" is selected

### ISSUE THREAD

**Issue by qualitypal** [Visionary-Versatilist/SmallFinance#44]
# Description
Add loan page has loan tenure type drop down disabled

# Steps to Reproduce
1. Login into Lendstack as superadmin
2. Click on Loan in left sidebar
3. Click on any loan displayed
4. Click on "Add Loan" button
5. Select "Installment Calculator" drop down on the top right corner
6. Observe drop down above Loan Tenure field

# Actual Result
Loan tenure type drop down is disabled

# Expected result
Loan tenure type drop down shall be enabled

# Test Environment
Instance: Staging
Browser: Chrome
branch: Main
OS: Mac

**Comment by Krithika-flink** [comment]
For Installment Calculator, It is disabled on purpose as it is EMI model...Only Monthly Installments are possible.
Hence, closing this defect.
