### ISSUE TITLE
[Update Password] Update Password is not working

### ISSUE THREAD

**Issue by qualitypal** [Visionary-Versatilist/SmallFinance#46]
# Description
Update password - User is not able to change the password

# Steps to Reproduce
1. Login into Lendstack as superadmin
2. Click on Profile on the left sidebar
3. Click on edit icon
4. Click on "Update Password?" link
5. Enter current password in Old password text box
6. Enter New password and confirm password
7. Click on Save

# Actual Result
No response shown to the user

# Expected Result
The password shall be updated and success message shall be displayed to the user

# Test Environment
Instance: Staging
OS: Mac
Browser: Chrome
Branch: Master

**Comment by Krithika-flink** [comment]
![image](https://user-images.githubusercontent.com/82878479/165937147-287aaccf-8764-4660-9edd-32f75311df51.png)
![image](https://user-images.githubusercontent.com/82878479/165937192-b1a6aa9d-db16-4c2f-a263-02ffd8dea1ee.png)

Password is getting updated in the database too while updating from the UI
