### ISSUE TITLE
[Edit Profile] User is not able to update profile

### ISSUE THREAD

**Issue by qualitypal** [Visionary-Versatilist/SmallFinance#47]
# Description
Could not edit profile of the user

# Steps to Reproduce
1. Login into Lendstack as superadmin
2. Click on Profile on the left sidebar
3. Click on edit icon
4. Change data in any text box
5. Click on Save

# Actual Result
User is shown success message but data is not updated 

# Expected Result
The data shall be updated

# Test Environment
Instance: Staging
OS: Mac
Browser: Chrome
Branch: Master

**Comment by Krithika-flink** [comment]
User Profile is getting updated without any issue.tested in all the text boxes.
