### ISSUE TITLE
Amortisation Schedule is populated only when Moratorium field is populated

### ISSUE THREAD

**Issue by qualitypal** [Visionary-Versatilist/SmallFinance#7]
Amortisation schedule is not populated in "Add Loan" Screen when Moratorium field is blank. 

#Severtiy: Medium
#Priority: Low

Steps to reproduce
================
1. Login into Lendstack as superadmin user
2. On Dashboard, click on Loans icon in sidebar
3. Click on Add Load button on the right corner
4. Select "Instalment Calculator" in drop down located at top right corner
5. Populate fields except "Moratorium" field
6. Click on Calculate button at the bottom

Actual Result:
===========
Only first line is populated in Amortisation Schedule 

Expected Result:
=============
Amortisation Schedule shall be populated with interest, principal, opening balance etc for all lines even if Moratorium field is left blank

Test Environment
==============
Browser: Chrome
Instance: Local
Node: 14.17.6
OS: Mac

<img width="1278" alt="image" src="https://user-images.githubusercontent.com/82005110/159028293-dab5890e-296e-46e3-b1cf-db884194f34e.png">

**Comment by Krithika-flink** [comment]
Issue is Fixed

**Comment by qualitypal** [comment]
Tested the Amortization scenario with Moratorium set to zero. Fix is working as expected
