### ISSUE TITLE
Add Loan Screen - Loan Parameters boundary is not checked

### ISSUE THREAD

**Issue by qualitypal** [Visionary-Versatilist/SmallFinance#8]
Add loan Screen has below loan parameters. Each parameter has range displayed on the screen. user inputs for these parameters are not validated for ranges mentioned on the screen
1. Loan Amount (INR 10 - INR 100000)
2. Loan Tenure (12 months - 60 months)
3. Rate of Interest (11% - 15%)

#Severity: Low
#priority: Low

Steps to Reproduce:
===============
1. Login into Lendstack as superadmin
2. on Dashboard, Click on Loans icons in left sidebar
3. Click on "Add Loan" button
4. Select "Installment Calculator" on the top right corner dropdown
5. Select an value for Loan Type dropdown 
6. Give values, for above mentioned loan parameters, that are out of range 

Actual Result:
===========
Amortisation Schedule is calculated for out-of-range values

Expected Result:
=============
User shall be show warning messages when out-of-range values are entered

Environment Tested:
===============
Browser: Chrome
Instance: Local
Node: 14.17.6
OS: Mac

**Comment by Krithika-flink** [comment]
Issue is fixed

**Comment by qualitypal** [comment]
Tested the ranges for amount, tenure, rate of interest. All working as expected
